---
title: "Density Estimation 2"
subtitle: "GMM. DBSCAN"
author: "Caballero Vergés Biel, Menzenbach Svenja and Reyes Illescas Kleber Enrique"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading libraries, include=FALSE}
library(mclust)
library(sm)
library(fpc)
library(dbscan)
```

```{r loading data}
load("BikeDay.Rdata")
X <- as.matrix(day[day$yr==1,c(10,14)])
#pairs(X)
```

# Questions

## 1. 
```{r question 1}
GMM_BIC <- Mclust(X,G=2:6, modelNames="VVV")
summary(GMM_BIC, parameters=F)
```
```{r question 1 - plots}

plot(GMM_BIC, what="BIC")
plot(GMM_BIC, what="classification")
plot(GMM_BIC, what="uncertainty")
plot(GMM_BIC, what="density")
```


## 2. 
```{r question 2}
#?sm.density

a = 0.25

plot(X, col=8)
sm.density(X,h=a*c(sd(day$temp), sd(day$casual)), 
           display="slice",col=2, props=c(25,50,75,95), add=TRUE)

# default props -> c(75,50,25)
```

## 3. 
```{r question 3}

k <- GMM_BIC$G
clust.ind <- GMM_BIC$classification

#plot(X, col=8)

plot(X,col=clust.ind)

a = 0.4

for (j in 1:k){
  cl.j <- (clust.ind==j)
  sm.density(X[cl.j,],h=a*c(sd(day$temp), sd(day$casual)), 
             display="slice",props=c(75),
             col=j, cex=4, add=TRUE)
}
```

## 4. 
```{r question 4}
#?fpc
cm <- mclustBIC(X,G=2:6,modelNames="VVV")
sum <- summary(cm, X)
cmnbhat <- mergenormals(X, sum, method="bhat")

plot(X, col=cmnbhat$clustering)

```

## 5. 
```{r question 5}
k_new <- length(cmnbhat$clusternumbers)
clust_merged.ind <- cmnbhat$clustering

#plot(X, col=8)

plot(X,col=clust_merged.ind)

a = 0.4

for (j in 1:k_new){
  cl.j <- (clust_merged.ind==j)
  sm.density(X[cl.j,],h=a*c(sd(day$temp), sd(day$casual)), 
             display="slice",props=c(75),
             col=j, cex=4, add=TRUE)
}
```

## 6. 
```{r question 6}
#?fpc::dbscan  / ?dbscan::dbscan
```

## 7. 
```{r question 7}

```

