---
title: "Local Poisson regression"
author: "Biel Caballero Vergés, Svenja Menzenbach and Kleber Enrique Reyes Illescas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Bandwidth choice for the local Poisson regression

```{r}
h.cv.sm.poisson <- function(x, y, rg.h = NULL, l.h = 10, method = loglik.CV) {
  cv.h <- numeric(l.h)
  
  if (is.null(rg.h)) {
    hh <- c(h.select(x, y, method = "cv"), h.select(x, y, method = "aicc"))
    rg.h <- range(hh) * c(1/1.1, 1.5)
  }
  
  gr.h <- exp(seq(log(rg.h[1]), log(rg.h[2]), length.out = l.h))
  
  for (i in 1:length(gr.h)) {
    cv.h[i] <- method(x, y, gr.h[i])
  }
  
  return(list(h = gr.h, cv.h = cv.h, h.cv = gr.h[which.max(cv.h)]))
}
```

```{r}
loglik.CV <- function(x, y, h) {
  n <- length(x)
  pred <- sapply(1:n, function(i, x, y, h) {
    sm.poisson(x = x[-i], y = y[-i], h = h, eval.points = x[i], display = "none")$estimate
  }, x, y, h)
  
  return(-sum(log(pred)) / n)
}
```


# 2. Local Poisson regression for Country Development Data

```{r}
# Load required library
library(sm)

countries <- read.csv2(file="HDI.2017.subset.csv",row.names = 1)

life.expec <- countries$Life.expec
le.fm.r <- round(countries$le.fm)

cv_result <- h.cv.sm.poisson(life.expec, le.fm.r, method = loglik.CV)

plot(cv_result$h, cv_result$cv.h)
selected.bandwidth <- cv_result$h.cv
abline(v = selected.bandwidth, col="8", lty=2)
mid.point <- (max(cv_result$cv.h)+min(cv_result$cv.h))/2
text(selected.bandwidth, mid.point, 
     round(selected.bandwidth*100)/100,cex=0.65, pos=4,col=1) 
lines(cv_result$h, cv_result$cv.h)

model <- sm.poisson(x = life.expec, y = le.fm.r, h = selected.bandwidth, col=1)
summary(model)

```
