---
title: "Density Estimation"
author: "Biel Caballero, Menzenbach Svenja and Reyes Illescas Kleber Enrique"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#1



#2
```{r CDrate}
cdrate.df <-read.table("./cdrate.dat.txt")
head(cdrate.df)
x <- cdrate.df[,1]
# sort(CDrate)
# # Stem-and-Leaf plot
# stem(CDrate)
```


```{r}
A <- min(x)-.05*diff(range(x)) 
Z <- max(x)+.05*diff(range(x))
nbr <- 7
hx <- hist(x,breaks=seq(A,Z,length=nbr+1),freq=F)
hx_f <- stepfun(hx$breaks,c(0,hx$density,0))
points(x, hx_f(x))

```

#3
```{r}
hx_f2<-length(x)/(length(x)-1)*hx_f(x)-1/((length(x)-1)*(hx$breaks[2]-hx$breaks[1]))

A <- min(x)-.05*diff(range(x)) 
Z <- max(x)+.05*diff(range(x))
nbr <- 7
hx <- hist(x,breaks=seq(A,Z,length=nbr+1),freq=F)
hx_f <- stepfun(hx$breaks,c(0,hx$density,0))
points(x, hx_f(x))
points(x, hx_f2, col="red")
```
#4
```{r}
looCV_log_lik_7 <- sum(log(hx_f2))
looCV_log_lik_7
```


#5
```{r}
#sum of the product of the hx_f2 vector plot histograms for different number of breaks nbr

log_liks = list()

for (i in c(1:15)){
  #A <- min(hx_f2)-.05*diff(range(hx_f2)) 
  #Z <- max(hx_f2)+.05*diff(range(hx_f2))
  nbr <- i
  hx_i <- hist(x,breaks=seq(A,Z,length=nbr+1),freq=F, plot = FALSE)
  hx_f_i <- stepfun(hx_i$breaks,c(0,hx_i$density,0))
  n <- length(x)
  b <- hx_i$breaks[2]-hx_i$breaks[1]
  hx_f2_i <- n/(n-1)*hx_f_i(x) - 1/((n-1)*b)
  print(min(hx_f2_i))
  
  hx_i <- hist(x,breaks=seq(A,Z,length=nbr+1),freq=F)
  points(x, hx_f_i(x))
  points(x, hx_f2_i, col='red')

  looCV_log_lik <- sum(log(hx_f2_i))
  log_liks <- append(log_liks, looCV_log_lik)
}
plot(seq(1, 15), log_liks)
nbr_opt <- which.max(log_liks)
hist(x,breaks=seq(A,Z,length=nbr_opt+1),freq=F)

# TODO: - avoid production of NaNs, 
#       - is it a problem that 'freq' is not used for some cases?

```



































