---
title: "Smoothing and regression splines"
author: "Biel Caballero Vergés, Svenja Menzenbach and Kleber Enrique Reyes Illescas"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading libraries, include=FALSE}
library(sm)
library(mgcv)
```

# Hirsutism dataset

## GAMs for hirsutism data
```{r}
hirs <- read.table("hirsutism.dat",header=T, sep="\t",fill=TRUE)

#summary(hirs)
attach(hirs)
```

```{r}
old.par<-par(mfrow=c(3,3))
for (j in 2:9) if (j != 5) hist(hirs[,j],main=names(hirs)[j])
par(old.par)
```

```{r}
apply(hirs[,-c(1,5)],2,sd, na.rm = T) # sd: standard deviation
```

```{r}
apply(hirs[,-c(1,5)],2,function(x){diff(range(x, na.rm = T))})
```

Possible groups of variables:
- FGm0, FGm3, FGm6
- SysPres, weigth
- DiaPres
- height


```{r}
gam_0 <- gam(FGm12 ~ FGm0 + SysPres + DiaPres + height + weight + Treatment)
summary(gam_0)
```

```{r} 
# we should not include FGm3 and FGm6
gam_1 <- gam(FGm12 ~ s(FGm0) + s(FGm3) + s(FGm6) + s(SysPres) + s(DiaPres) + s(height) + s(weight), data=hirs)
summary(gam_1)
```

It seems that FG3 and SysPres are both linear. FGm6 and height are quadratic

```{r}
plot(gam_1,residuals=TRUE, shade=TRUE, cex=2, lwd=2)
```
```{r}
vis.gam(gam_1, view=c("FGm0","weight"), plot.type = "persp")
```

```{r}
vis.gam(gam_1, view=c("height","weight"), plot.type = "persp")
```

```{r}
gam.check(gam_1)
```


```{r}
gam_2 <- gam(FGm12 ~ s(FGm0, by=Treatment) + s(SysPres, by=Treatment) + s(DiaPres, by=Treatment) + s(height, by=Treatment) + s(weight, by=Treatment))
summary(gam_2)
```


```{r}
# multiple linear regression
gam_0.1 <- gam(FGm12 ~ FGm0 + SysPres + DiaPres + height + weight + Treatment)
summary(gam_0.1)
```

```{r}
# generative additive model
gam_1.1 <- gam(FGm12 ~ s(FGm0, by=Treatment) + s(SysPres, by=Treatment) + s(DiaPres, by=Treatment) + s(height, by=Treatment) + s(weight, by=Treatment))
summary(gam_1.1)
```

```{r}
# Generalized nonparametric multiple regression model
gam_2.1 <- gam(FGm12 ~ te(FGm0, weight)) # SysPres, DiaPres, height, Treatment)
summary(gam_2.1)
```
```{r}
# semiparametric model - FGmO
gam_3.1 <- gam(FGm12 ~ FGm0 + s(SysPres, by=Treatment) + s(DiaPres, by=Treatment) + s(height, by=Treatment) + s(weight, by=Treatment))
summary(gam_3.1)
```
```{r}
# semiparametric model - SysPres (low df at model 0)
gam_4.1 <- gam(FGm12 ~ s(FGm0s, by=Treatment) + SysPres + s(DiaPres, by=Treatment) + s(height, by=Treatment) + s(weight, by=Treatment))
summary(gam_4.1)
```

```{r}
# semiparametric model - FGmO + SysPres
gam_5.1 <- gam(FGm12 ~ FGm0 + SysPres + s(DiaPres, by=Treatment) + s(height, by=Treatment) + s(weight, by=Treatment))
summary(gam_5.1)
```

```{r}
plot(gam_1, residuals = TRUE,
     shade=TRUE, cex=2, lwd=2, 
     shift = gam_1$coefficients[1],
     seWithMean=TRUE,
     main=paste("Equiv. no. params.=",
                round(sum(gam_1$edf),2)))
```
```{r}
vis.gam(gam_1,view=c("FGm0","Treatment"),
        theta = 40, phi = 40, r = sqrt(3), d = 1,)
```


## Anova tests

```{r}
anova(gam_0,gam_1,test="F")
anova(gam_0,gam_2,test="F")
anova(gam_0,gam_3,test="F")
#anova(gam_0,gam_4,test="F")
#anova(gam_0,gam_5,test="F")
anova(gam_1, gam_2)
anova(gam_1, gam_3)
```















